### ISSUE TITLE
ImportError: No module named coros

### ISSUE THREAD

**Issue by sn01615** [pricingassistant/mrq#157]
install: pip install mrq
system: centos7 x64

```
# mrq-run --queue fetches tasks.Fetch url http://www.google.com
Traceback (most recent call last):
  File "/bin/mrq-run", line 9, in <module>
    load_entry_point('mrq==0.1.18', 'console_scripts', 'mrq-run')()
  File "/usr/lib/python2.7/site-packages/mrq/bin/mrq_run.py", line 33, in main
    set_current_config(cfg)
  File "/usr/lib/python2.7/site-packages/mrq/context.py", line 82, in set_current_config
    patch_import()
  File "/usr/lib/python2.7/site-packages/mrq/monkey.py", line 127, in patch_import
    import gevent.coros
  File "/usr/lib64/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named coros
```

**Comment by sylvinus** [comment]
Hello @sn01615 . This issue was already fixed in master, so I pushed a new version `0.2.0` on pypi. Can you confirm it works for you?

Thanks,
