### ISSUE TITLE
OperationFailure: WiredTigerIndex::insert: key too large to index

### ISSUE THREAD

**Issue by functure** [pricingassistant/mrq#178]
```
Traceback (most recent call last):
  File "/home/usom/.local/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/usom/.local/lib/python2.7/site-packages/mrq/worker.py", line 166, in greenlet_scheduler
    scheduler.sync_tasks(self.config.get("scheduler_tasks") or [])
  File "/home/usom/.local/lib/python2.7/site-packages/mrq/scheduler.py", line 56, in sync_tasks
    self.collection.find_one_and_update({"hash": task["hash"]}, {"$set": task}, upsert=True)
  File "/home/usom/.local/lib/python2.7/site-packages/mrq/monkey.py", line 99, in mrq_monkey_patched
    ret = base_method(self, *args, **kwargs)
  File "/home/usom/.local/lib/python2.7/site-packages/pymongo/collection.py", line 2422, in find_one_and_update
    sort, upsert, return_document, **kwargs)
  File "/home/usom/.local/lib/python2.7/site-packages/pymongo/collection.py", line 2198, in __find_and_modify
    collation=collation)
  File "/home/usom/.local/lib/python2.7/site-packages/pymongo/collection.py", line 232, in _command
    collation=collation)
  File "/home/usom/.local/lib/python2.7/site-packages/pymongo/pool.py", line 419, in command
    collation=collation)
  File "/home/usom/.local/lib/python2.7/site-packages/pymongo/network.py", line 116, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/home/usom/.local/lib/python2.7/site-packages/pymongo/helpers.py", line 210, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
OperationFailure: WiredTigerIndex::insert: key too large to index, failing  50510
```

I am trying to create a scheduler task which obtains a large dict of params and getting this error when I start a worker. As far as I can see this is because of indexing limitations of mongodb. Is there a workaround for that? If there is not, can you provide a fix or I can patch the code if you lead me the way.

**Comment by sylvinus** [comment]
Hi!

This is indeed a design limitation.

If you are configuring your task to be scheduled I guess your big dict of parameters is relatively static? Can't you just pass a smaller identifier for it to the task?

In general, task parameters should be as small as possible.

**Comment by functure** [comment]
Task parameters are configurable from a user interface. User can add thousands of entries for just one task if s/he wishes to. I have tried to pickle and encode the parameters to shrink the size and decode-unpickle at job body but that doesn't give much benefit.

I have come up with a temporary solution. I am setting `failIndexKeyTooLong` parameter of mongodb to `false` . I think job is not indexed but I can still find it writing a query. I hope it does not create a problem in future.

Thank you for your help.

**Comment by sylvinus** [comment]
I think the real solution would be to store those parameters in a separate database, get an ID for each set of them, and then just pass that single ID to the task. But it's up to you!

Best,
